id: I0A004040
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:16:52+00:00'
last_modified: '2022-06-07T15:03:16.294890+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159444
  title: ཁམས་ཀྱི་མ་ཡུམ་འབུམ་མཚོ་ཕྱུག་མོའི་གནས་ཡིག་ངོ་མཚར་བྱེ་བའི་རླབས་ཕྲེང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    3B55:
      image_group_id: I2PD19059
      title: ''
      total_pages: 200
      order: 1
      base_file: 3B55.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
