id: P001760
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159444
  title: ཁམས་ཀྱི་མ་ཡུམ་འབུམ་མཚོ་ཕྱུག་མོའི་གནས་ཡིག་ངོ་མཚར་བྱེ་བའི་རླབས་ཕྲེང་།
  author: ''
  volumes:
    83d4e467b0ee4e5f86aeb35dae2675e4:
      image_group_id: I2PD19059
      title: ''
      volume_number: 1
      total_pages: 200
      base_file: v001.txt
